name: production

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  create-tag-release:
    runs-on: ubuntu-latest
    outputs:
      tag-version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout branch master
        uses: actions/checkout@v2

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          target_commitish: master
          draft: false
          prerelease: false
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run Tests
      run: |
        npm install
        npm run test:ci
        npm build
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: |
        docker build -t henriquequeirozcunha/clean-node-api:latest .
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/clean-node-api

